// <auto-generated />
using AspNetCoreIHostedService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspNetCoreIHostedService.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    partial class WeatherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreIHostedService.Model.WeatherData", b =>
                {
                    b.Property<string>("CityName")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Humidity");

                    b.Property<double>("Lat");

                    b.Property<double>("Lon");

                    b.Property<string>("MainWeather");

                    b.Property<int>("Pressure");

                    b.Property<double>("Temperature");

                    b.Property<string>("WeatherDescription");

                    b.HasKey("CityName");

                    b.ToTable("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
