// <auto-generated />
using AspNetCoreIHostedService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AspNetCoreIHostedService.Migrations
{
    [DbContext(typeof(WeatherDbContext))]
    [Migration("20170928202212_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreIHostedService.Model.MaxMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Humidity");

                    b.Property<DateTime>("MeasureTime");

                    b.Property<double>("Pressure");

                    b.Property<double>("Temperature");

                    b.HasKey("Id");

                    b.ToTable("MaxMeasures");
                });

            modelBuilder.Entity("AspNetCoreIHostedService.Model.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<double>("Humidity");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<double>("Lat");

                    b.Property<double>("Lon");

                    b.Property<string>("MainWeather")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Pressure");

                    b.Property<double>("Temperature");

                    b.Property<string>("WeatherDescription")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("WeatherData");
                });
#pragma warning restore 612, 618
        }
    }
}
